### ISSUE TITLE
Cuidado con las letras

### ISSUE THREAD

**Issue by pabloleonalcaide** [NievesBorrero/TopMusic#4]
Vigila las "eñes", te puede saltar algún símbolo extraño

https://github.com/NievesBorrero/TopMusic/blob/master/TestTopMusic.java#L119

https://github.com/NievesBorrero/TopMusic/blob/master/TestTopMusic.java#L122

**Comment by NievesBorrero** [comment]
Jaja cierto!

**Comment by NievesBorrero** [comment]
hecho!
