### ISSUE TITLE
los javadocs

### ISSUE THREAD

**Issue by pabloleonalcaide** [NievesBorrero/TopMusic#5]
Introduce los comentarios en el método  @NievesBorrero 
https://github.com/NievesBorrero/TopMusic/blob/master/TestTopMusic.java#L49`

**Comment by NievesBorrero** [comment]
Lo haré, gracias Pablo :)

**Comment by NievesBorrero** [comment]
Lo haré, gracias @pabloleonalcaide :)

**Comment by pabloleonalcaide** [comment]
De nada, para eso estamos!

**Comment by NievesBorrero** [comment]
Cambiado :)
